// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCSR_UJH5f_volMrRFX2MYPXpm4lZO7Y',
    appId: '1:784144455680:web:d0c8178a06543770a420e5',
    messagingSenderId: '784144455680',
    projectId: 'easymoney-8e9bb',
    authDomain: 'easymoney-8e9bb.firebaseapp.com',
    storageBucket: 'easymoney-8e9bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7UJpvboNq5RguDYduA_RnpX_RRN4mvE',
    appId: '1:784144455680:android:ec63b9de047393e5a420e5',
    messagingSenderId: '784144455680',
    projectId: 'easymoney-8e9bb',
    storageBucket: 'easymoney-8e9bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9ubwzQu2dyjIH7TnJgzqFAxYsUrpqzM',
    appId: '1:784144455680:ios:acf7a747a5dcd009a420e5',
    messagingSenderId: '784144455680',
    projectId: 'easymoney-8e9bb',
    storageBucket: 'easymoney-8e9bb.firebasestorage.app',
    iosBundleId: 'com.easymoney.app.easymoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq9ubwzQu2dyjIH7TnJgzqFAxYsUrpqzM',
    appId: '1:784144455680:ios:acf7a747a5dcd009a420e5',
    messagingSenderId: '784144455680',
    projectId: 'easymoney-8e9bb',
    storageBucket: 'easymoney-8e9bb.firebasestorage.app',
    iosBundleId: 'com.easymoney.app.easymoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSCSR_UJH5f_volMrRFX2MYPXpm4lZO7Y',
    appId: '1:784144455680:web:5c05da2ab746e2eea420e5',
    messagingSenderId: '784144455680',
    projectId: 'easymoney-8e9bb',
    authDomain: 'easymoney-8e9bb.firebaseapp.com',
    storageBucket: 'easymoney-8e9bb.firebasestorage.app',
  );
}
